### PR TITLE
Update default version to eXist 3.0

### PR DESCRIPTION
**Pull request by adamretter**
I think this should be updated. Is that correct?

### CODE REVIEW

**Comment by joewiz** [comment]
Have you, by chance, tested an installation of 2.2 requesting available packages from a public-repo instance with this change? 

I'm not sure, but my worry is that this change could prevent 2.2 users from seeing 2.2-compatible packages. I believe this default was added because pre-2.2 versions of eXist didn't include version as part of the query parameter. The 2.2 default had the effect of assuming all packages in the repo are compatible with 2.2 unless they declare a higher version in their package metadata.

**Comment by adamretter** [comment]
@joewiz Okay, then I completely misunderstood what this was for ;-)

**Comment by joewiz** [comment]
@wolfgangmm Could you please confirm/correct my understanding? I'd gladly add a comment to the code explaining the intention of the `$list:DEFAULT_VERSION` just above variable declaration at https://github.com/eXist-db/public-xar-repo/blob/master/modules/list.xql#L11.

**Comment by wolfgangmm** [comment]
@joewiz you are right, the default version was set to 2.2 because this version was the last one known to work most of the older packages. If a client does not send a version parameter, it is assumed to be 2.2 or older.

**Comment by joewiz** [comment]
@wolfgangmm Thanks, I've filed a PR adding this info.

**Pull request closed without merging**
